import type { NextPage } from 'next'
import { useRouter } from 'next/router'
import { useRef, useEffect } from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { io } from 'socket.io-client'
const socket = io({ path: '/api/join' })

const Home: NextPage = () => {
  const screen: any = useRef()
  const router = useRouter()

  const room = router.query.room || 230322

  useEffect(() => {
    navigator.mediaDevices
      .getDisplayMedia({
        video: true,
        audio: false,
      })
      .then((stream) => {
        screen.current.srcObject = stream
      })
  })

  socket.on('connect', () => {
    console.log('SOCKET CONNECTED!', socket.id)
    const userData = {
      userID: socket.id,
      roomID: room,
    }
    socket.emit('join-room', userData)
  })

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <video
          ref={screen}
          autoPlay
          style={{ border: '1px solid #999', height: '100vh', width: '100vh' }}
        ></video>
      </main>
    </div>
  )
}

export default Home
